name: InferFace
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python>=3.6,<3.9
  - pip
  - cudatoolkit=11.0
  - jupyter
  - numpy
  - pandas
  - pytorch
  - seaborn
  - torchvision
  - pytorch-lightning
  - tqdm
  - pip:
      - facenet-pytorch
